//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKinhDoanhNhaThuoc.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_CUNGCAP_THUOC
    {
        public string ma_ctccthuoc { get; set; }
        public Nullable<int> so_luong { get; set; }
        public System.DateTime ngay { get; set; }
        public string ma_nhacungcap { get; set; }
        public string ma_hangthuoc { get; set; }
    
        public virtual HANG_THUOC HANG_THUOC { get; set; }
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
    }
}
