//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKinhDoanhNhaThuoc.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_XUAT_HD_THUOC
    {
        public string ma_ctxuathdthuoc { get; set; }
        public Nullable<int> so_luong { get; set; }
        public string ma_thuoc { get; set; }
        public string ma_hoadon { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
