//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKinhDoanhNhaThuoc.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        public HOA_DON()
        {
            this.CT_XUAT_HD_THUOC = new HashSet<CT_XUAT_HD_THUOC>();
        }
    
        public string ma_hoadon { get; set; }
        public System.DateTime ngay { get; set; }
        public string ma_thuoc { get; set; }
        public string ma_nhacungcap { get; set; }
    
        public virtual ICollection<CT_XUAT_HD_THUOC> CT_XUAT_HD_THUOC { get; set; }
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
