//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKinhDoanhNhaThuoc.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        public string ma_khachhang { get; set; }
        public string hodem { get; set; }
        public string ten { get; set; }
        public Nullable<int> sodienthoai { get; set; }
        public string dia_chi { get; set; }
        public string ma_nhanvien { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
