//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKinhDoanhNhaThuoc.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_THUOC
    {
        public LO_THUOC()
        {
            this.THUOCs = new HashSet<THUOC>();
        }
    
        public string ma_lothuoc { get; set; }
        public System.DateTime ngay_sanxuat { get; set; }
        public System.DateTime ngay_hethan { get; set; }
    
        public virtual ICollection<THUOC> THUOCs { get; set; }
    }
}
