//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKinhDoanhNhaThuoc.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHA_CUNG_CAP
    {
        public NHA_CUNG_CAP()
        {
            this.CT_CUNGCAP_THUOC = new HashSet<CT_CUNGCAP_THUOC>();
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public string ma_nhacungcap { get; set; }
        public string ten_nhacungcap { get; set; }
        public string dia_chi { get; set; }
        public int sodienthoai { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<CT_CUNGCAP_THUOC> CT_CUNGCAP_THUOC { get; set; }
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
    }
}
