//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKinhDoanhNhaThuoc.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {
        public NHAN_VIEN()
        {
            this.KHACH_HANG = new HashSet<KHACH_HANG>();
            this.THUOCs = new HashSet<THUOC>();
        }
    
        public string ma_nhanvien { get; set; }
        public string hodem { get; set; }
        public string ten { get; set; }
        public System.DateTime nam_sinh { get; set; }
        public Nullable<int> sodienthoai { get; set; }
        public string diachi { get; set; }
    
        public virtual ICollection<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual ICollection<THUOC> THUOCs { get; set; }
    }
}
