//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKinhDoanhNhaThuoc.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAI_KHOAN
    {
        public string ma_taikhoan { get; set; }
        public string tai_khoan1 { get; set; }
        public string mat_khau { get; set; }
    }
}
