//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKinhDoanhNhaThuoc.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUOC
    {
        public THUOC()
        {
            this.CT_XUAT_HD_THUOC = new HashSet<CT_XUAT_HD_THUOC>();
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public string ma_thuoc { get; set; }
        public string ten_thuoc { get; set; }
        public string thanh_phan { get; set; }
        public string cong_dung { get; set; }
        public string ma_loaithuoc { get; set; }
        public string ma_nhanvien { get; set; }
        public string ma_lothuoc { get; set; }
    
        public virtual ICollection<CT_XUAT_HD_THUOC> CT_XUAT_HD_THUOC { get; set; }
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        public virtual LO_THUOC LO_THUOC { get; set; }
        public virtual LOAI_THUOC LOAI_THUOC { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
